In [1]:
import numpy as np

In [2]:
# Array
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
a.shape

(2, 2)

In [4]:
a = a.reshape(1,4)

In [5]:
a

array([[1, 2, 3, 4]])

In [6]:
# dot

''' This function returns the product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.
For 1-D arrays, it is the inner product of the vectors. For N- dimensional array, it is a sum product over the last axis of a and the second axis of b'''


' This function returns the product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.\nFor 1-D arrays, it is the inner product of the vectors. For N- dimensional array, it is a sum product over the last axis of a and the second axis of b'

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

print("a :", a)
print()
print("b :", b)
print()
print("a x b =", np.dot(a,b))

a : [[1 2]
 [3 4]]

b : [[11 12]
 [13 14]]

a x b = [[37 40]
 [85 92]]


In [14]:
#Random() function:
''' Syntax : numpy.random.random(size=None)
Parameters:
size: [int or tuple of ints, optional]
Output shape. if the given shape is e.g., (m,n,k), then m*n*k samples are drawn.'''

' Syntax : numpy.random.random(size=None) \nParameters: \nsize: [int or tuple of ints, optional] \nOutput shape. if the given shape is e.g., (m,n,k), then m*n*k samples are drawn.'

In [16]:
# Output array
out_arr = np.random.random(size =3)
print(out_arr)
print(np.random.random((2,3)))

[0.00691974 0.02179334 0.81034342]
[[0.3337699  0.31200303 0.92461662]
 [0.00566248 0.61018094 0.56145154]]


In [17]:
# Slicing
a = np.random.random((5,3))
a

array([[0.72454456, 0.59999898, 0.19166473],
       [0.05934737, 0.06523998, 0.13972579],
       [0.7800234 , 0.86825809, 0.74550203],
       [0.60000212, 0.90842823, 0.79858926],
       [0.30450825, 0.24239385, 0.73673731]])

In [18]:
a.shape

(5, 3)

In [19]:
a[1:3,1:3]

array([[0.06523998, 0.13972579],
       [0.86825809, 0.74550203]])

In [20]:
a[:,:2]

array([[0.72454456, 0.59999898],
       [0.05934737, 0.06523998],
       [0.7800234 , 0.86825809],
       [0.60000212, 0.90842823],
       [0.30450825, 0.24239385]])

In [21]:
# Sum()function:
''' numpy .sum(arr,axis,dtype,out):
This function returns the sum of array elements over the specified axis.'''

' numpy .sum(arr,axis,dtype,out):\nThis function returns the sum of array elements over the specified axis.'

In [22]:
# 1-D array
arr =[20,2,.4, 10, 4]

print("Sum of arr :" , np.sum(arr))

Sum of arr : 36.4


In [23]:
arr = [[0,1],[0,5]]
np.sum(arr, axis= 0)

array([0, 6])

In [24]:
np.sum(arr)

6

In [25]:
# Square()function:
'''This mathematical function helps user to calculate square value of each element in the array.'''

'This mathematical function helps user to calculate square value of each element in the array.'

In [26]:
arr1 = [1,-3,8,34]
print("Squared no. of arr1 = \n", np.square(arr1))

Squared no. of arr1 = 
 [   1    9   64 1156]
